### ISSUE TITLE
Ability to choose download location. 

### ISSUE THREAD

**Issue by zerobun** [jerry08/Yosu#1]
As the title suggests, it would be perfect to be able to choose the download location of the music in settings.

And thank you for thr amazing app, I found this as the only app which actually searches properly from Spotify and actually let's you download from there rather than saying it downloads from Spotify and downloads the music from YouTube or something.

**Comment by jerry08** [comment]
Thanks! I'll work on the suggestions you made

**Comment by zerobun** [comment]
> Thanks! I'll work on the suggestions you made

Thank you for looking into it really appreciate the work and good luck 😊❤️
