### ISSUE TITLE
The type initializer for '<Module>' threw an exception.

### ISSUE THREAD

**Issue by yri066** [jerry08/Yosu#9]
The release application does not run, an exception is thrown when trying to compile and run it on its own.
Phone OnePlus 9R Android 11
![image](https://github.com/user-attachments/assets/8080979a-0788-4358-9ac7-923d392e5585)

**Comment by yri066** [comment]
When running in emulator the same situation, Android 15

![image](https://github.com/user-attachments/assets/9b439ffc-f125-46c6-984b-3ca93ce52f90)

**Comment by yri066** [comment]
I found out that an exception occurs in the application if the system language is Russian or Belarusian, because of the policy of the Ukrainian developers YoutubeExplode, this library specially creates an unhandled exception.

**Comment by jerry08** [comment]
Well that sucks. For now, you can download YoutubeExplode repo, remove `Deorcify` NuGet package and reference that project in Yosu instead.
